### ISSUE TITLE
TypeError: <lambda>() missing 1 required positional argument: 

### ISSUE THREAD

**Issue by aleksandrasurbonas** [Bibyutatsu/Self_Driving_Car#1]
Running `window.py` with `chipmunk` 6.0.0 or higher stops with error (Output below).
Found a decent possible solution https://stackoverflow.com/a/67555588/5548699.
Would it be hard to update the `Vec2D` class instances?

Output:
```
From cffi callback <function SpaceDebugDrawOptions.__init__.<locals>.f6 at 0x00000078853049D0>:
Traceback (most recent call last):
  File "C:\Python\Python39\site-packages\pymunk\space_debug_draw_options.py", line 138, in f6
    return self.color_for_shape(shape)
  File "C:\Python\Python39\site-packages\pymunk\space_debug_draw_options.py", line 345, in color_for_shape
    return SpaceDebugColor(*shape.color)  # type: ignore
TypeError: <lambda>() missing 1 required positional argument: 'a'

Traceback (most recent call last):
  File "C:\git\Self_Driving_Car\window.py", line 129, in <module>
    pyglet.app.run()
  File "C:\Python\Python39\site-packages\pyglet\app\__init__.py", line 107, in run
    event_loop.run()
  File "C:\Python\Python39\site-packages\pyglet\app\base.py", line 167, in run
    timeout = self.idle()
  File "C:\Python\Python39\site-packages\pyglet\app\base.py", line 237, in idle
    redraw_all = self.clock.call_scheduled_functions(dt)
  File "C:\Python\Python39\site-packages\pyglet\clock.py", line 292, in call_scheduled_functions
    item.func(now - item.last_ts, *item.args, **item.kwargs)
  File "C:\git\Self_Driving_Car\window.py", line 105, in update
    cars[i].drive()
  File "C:\git\Self_Driving_Car\car.py", line 196, in drive
    self.update_reward()
  File "C:\git\Self_Driving_Car\car.py", line 225, in update_reward
    if self.reward() > self.reward_val:
  File "C:\git\Self_Driving_Car\car.py", line 199, in reward
    current_pos = Vec2d(self.car_body.position)
TypeError: <lambda>() missing 1 required positional argument: 'y'
```

**Comment by aleksandrasurbonas** [comment]
I have updated car.py locally, where I have tried to update Vec2D instances from `Vec2D(3,4)` to `Vec2D(*(3,4))` as per answer above. I was able to run the program to see the pyglet window, but now it a question of shape missing a color attribute:

```
Traceback (most recent call last):
  File "C:\Python\Python39\site-packages\pymunk\space_debug_draw_options.py", line 138, in f6
    return self.color_for_shape(shape)
  File "C:\Python\Python39\site-packages\pymunk\space_debug_draw_options.py", line 345, in color_for_shape
    return SpaceDebugColor(*shape.color)  # type: ignore
TypeError: <lambda>() missing 1 required positional argument: 'a'
Epoch:  1  Reward stats:  (35.62399310565041, 39.679748592962326, 63.92174541551774)
Epoch:  2  Reward stats:  (39.98537569829106, 47.30673284647638, 77.79452711552044)
```

**Comment by aleksandrasurbonas** [comment]
> 
> 
> I have updated car.py locally, where I have tried to update Vec2D instances from `Vec2D(3,4)` to `Vec2D(*(3,4))` as per answer above. I was able to run the program to see the pyglet window, but now it a question of shape missing a color attribute:
> 
> ```
> Traceback (most recent call last):
>   File "C:\Python\Python39\site-packages\pymunk\space_debug_draw_options.py", line 138, in f6
>     return self.color_for_shape(shape)
>   File "C:\Python\Python39\site-packages\pymunk\space_debug_draw_options.py", line 345, in color_for_shape
>     return SpaceDebugColor(*shape.color)  # type: ignore
> TypeError: <lambda>() missing 1 required positional argument: 'a'
> Epoch:  1  Reward stats:  (35.62399310565041, 39.679748592962326, 63.92174541551774)
> Epoch:  2  Reward stats:  (39.98537569829106, 47.30673284647638, 77.79452711552044)
> ```

Fixed by updating `color` tuples to have four elements as given in http://www.pymunk.org/en/latest/pymunk.html#pymunk.SpaceDebugDrawOptions.color_for_shape.
